import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import "./StarWarsText.css";
import { setIntro } from "../../redux/slices/isSkipedIntro";

const StarWarsText = () => {
    const [isPaused, setIsPaused] = useState(false);
    // const [isSkiped, setIsSkiped] = useState(false);
    const [animatePause, setAnimatePause] = useState(false);
    const [animateSkip, setAnimateSkip] = useState(false);
    const isSkiped = useSelector(state => state.introReducer.intro.intro);
    const dispatch = useDispatch();

    console.log(isSkiped);

    const toggleAnimation = () => {
        setIsPaused(!isPaused);
      };

    const setIsSkiped = () => {
      dispatch(setIntro({
        intro: true
      }));
    }

      useEffect(() => {
        const triggerAnimationPause = () => {
            setAnimatePause(true);
            // setTimeout(() => setAnimatePause(false), 2000);
        };
        // triggerAnimationPause();
        const interval = setInterval(triggerAnimationPause, 1000);
        return () => clearInterval(interval);

    }, []);

      useEffect(() => {
        const triggerAnimationSkip = () => {
            setAnimateSkip(true);
            // setTimeout(() => setAnimateSkip(false), 2000);
        };
        // triggerAnimationSkip();
        const interval = setInterval(triggerAnimationSkip, 2000);
        return () => clearInterval(interval);

    }, []);

  return (
    <div className={`${!isSkiped ? "star-wars-container" : "d-none"}`}>
      {/* <div className={`star-wars-text ${isPaused ? "paused" : ""}`}>
        <p>
            Far in the future, people will have the opportunity to visit unexplored worlds, participate in the creation of space
            colonies, communicate with new types of minds, and achieve perfection and harmony both in their physical         
            bodies and in their mentality. And, finally, the changed person at that time will turn old age and death into relics of
            the past. The problem of diseases will lose its relevance, and real euphoria will come from the process of life.
        </p>
        <p>
            But what should a person of our time do? What should one do who dreams not only to see but also to take part
            in exciting journeys through the universe, in the discovery of new worlds, and also to reveal the secrets of
            the unknown? How to find hope for an incurable patient if the possibility of treatment will appear only in
            the immeasurable future?
        </p>
        <p>
            The company "Tours to the Future" provides such an opportunity and hope. For a symbolic price, a person is
            given unique tours  into the future, starting from the twenty-second century, where technology is not yet at
            the highest level but it is easier to master it and ending with the thirty-third century, where the real and parallel
            worlds have been fully explored, and the person himself has been improved. In addition to the tour, you can
            purchase robots and vehicles corresponding to the era to which the tourist is going.
        </p>
        <p>
            However, in order not to violate the laws of time balance, the purchased tour can be used only 8 minutes after 
            death, which will not be specially arranged for this purpose. From the moment of buying a tour, a new section is formed in the neocortex of the person, <br />
            which is generated by the portal. It is this portal that will be the key part of the transfer of consciousness from the dying brain to another time.            
        </p>
        <p>
            Give real hope to yourself or someone who may be terminally ill by using the services of our company for purchasing tours to a bright future!
        </p>
      </div> */}
      <div className={`star-wars-text ${isPaused ? "paused" : ""}`}>
        <p>
            Далеко в майбутньому у людей з'явиться можливість відвідувати незвідані світи, брати участь 
            у створенні космічних колоній, спілкуватися з новими видами розуму, досягати досконалості та 
            гармонії як у своєму фізичному тілі, так і у своїй ментальності. І, нарешті, видозмінена 
            на той час людина перетворить старість і смерть на пережитки минулого. Проблема хвороб втратить 
            свою актуальність і настане реальна ейфорія від процесу життя.
        </p>
        <p>
            Але що робити людині нашого часу? Що робити тому, хто мріє не лише побачити, а й взяти участь 
            у захоплюючих подорожах Всесвітом, у відкритті нових світів, а також розкрити таємниці непізнаного. 
            Як знайти надію невиліковному хворому, якщо можливість лікування з'явиться тільки в неосяжному майбутньому?
        </p>
        <p>
            Таку можливість та надію надає компанія "Tours to the future". За символічну ціну людині надаються унікальні 
            тури в майбутнє, починаючи з двадцять другого століття, де технології ще не на вищому рівні, але тим легше 
            їхнє освоєння, і закінчуючи тридцять третім століттям, де повною мірою вивчені реальні та паралельні світи 
            та вдосконалена сама людина. До туру додатково можна придбати роботів і транспорт, що відповідають тій епосі, 
            в яку прямує турист.
        </p>
        <p>
            Однак, щоб не порушувати закони балансу часу, придбаним туром можна скористатися лише через 8 хвилин після смерті, 
            яка не буде спеціально влаштована для цієї мети. З моменту покупки туру в корі головного мозку людини формується нова 
            ділянка, яка генерує портал. Саме цей портал і буде ключовою ланкою перенесення свідомості з мозку, що відживає, 
            в інший час.
        </p>
        <p>
            Подаруйте реальну надію собі чи комусь, можливо, невиліковно хворому, скориставшись послугами нашої компанії з 
            придбання турів у світле майбутнє!
        </p>
      </div>
      <button onClick={toggleAnimation} className={`toggle-button-pause ${animatePause ? "pulse" : ""}`}>
        {isPaused ? "Resume" : "Pause"}
      </button>
      <button onClick={setIsSkiped} className={`toggle-button-skip ${animateSkip ? "pulse" : ""}`}>
        Skip
      </button>
    </div>
  );
};

export default StarWarsText;